-- AI Features Tables for Separate Microservice
-- Added: 2025-10-09
-- Description: Database schema for AI-powered features (summaries, quizzes, transcripts)
-- managed by separate microservice. These tables are accessed by the external AI service
-- and do not affect core Tobira functionality.

-- ============================================
-- Video Transcripts
-- ============================================
-- Stores video transcripts uploaded externally or synced from Opencast.
-- The AI microservice uses these as input for generating summaries and quizzes.

create table if not exists video_transcripts (
    id bigserial primary key,
    event_id bigint not null references all_events(id) on delete cascade,
    language varchar(10) not null default 'en',
    content text not null,
    source varchar(50) not null default 'manual_upload',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(event_id, language)
);

create index idx_video_transcripts_event_id on video_transcripts(event_id);

comment on table video_transcripts is 
    'Video transcripts managed by AI microservice. Used as input for AI features.';
comment on column video_transcripts.source is 
    'Source of transcript: manual_upload, opencast, auto_generated';


-- ============================================
-- AI-Generated Summaries
-- ============================================
-- Stores AI-generated summaries of video content.
-- Generated by the external AI microservice using OpenAI API.

create table if not exists ai_summaries (
    id bigserial primary key,
    event_id bigint not null references all_events(id) on delete cascade,
    language varchar(10) not null default 'en',
    summary text not null,
    model varchar(50) not null,
    processing_time_ms integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(event_id, language)
);

create index idx_ai_summaries_event_id on ai_summaries(event_id);

comment on table ai_summaries is 
    'AI-generated video summaries from external microservice';
comment on column ai_summaries.model is 
    'OpenAI model used (e.g., gpt-3.5-turbo, gpt-4)';
comment on column ai_summaries.processing_time_ms is 
    'Time taken to generate summary in milliseconds';


-- ============================================
-- AI-Generated Quizzes
-- ============================================
-- Stores AI-generated interactive quizzes for videos.
-- Quiz data is stored as JSONB for flexibility.

create table if not exists ai_quizzes (
    id bigserial primary key,
    event_id bigint not null references all_events(id) on delete cascade,
    language varchar(10) not null default 'en',
    quiz_data jsonb not null,
    model varchar(50) not null,
    processing_time_ms integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(event_id, language),
    constraint valid_quiz_data check (
        jsonb_typeof(quiz_data) = 'object' 
        and quiz_data ? 'questions'
        and jsonb_typeof(quiz_data->'questions') = 'array'
    )
);

create index idx_ai_quizzes_event_id on ai_quizzes(event_id);

comment on table ai_quizzes is 
    'AI-generated interactive quizzes from external microservice';
comment on column ai_quizzes.quiz_data is 
    'Quiz questions and metadata in JSON format';


-- ============================================
-- AI Configuration
-- ============================================
-- Configuration and feature flags for AI features.
-- Allows runtime control without code changes.

create table if not exists ai_config (
    id bigserial primary key,
    key varchar(100) not null unique,
    value jsonb not null,
    description text,
    updated_at timestamptz not null default now()
);

comment on table ai_config is 
    'Configuration for AI features (feature flags, model selection, etc.)';

-- Insert default configuration values
insert into ai_config (key, value, description) values
    ('features_enabled', 'false', 'Master switch for AI features - set to true to enable'),
    ('default_model', '"gpt-3.5-turbo"', 'Default OpenAI model to use for generation'),
    ('cache_ttl_seconds', '3600', 'Cache TTL for AI responses (1 hour default)'),
    ('max_transcript_length', '50000', 'Maximum transcript length for processing'),
    ('summary_enabled', 'true', 'Enable summary generation feature'),
    ('quiz_enabled', 'false', 'Enable quiz generation feature (Phase 2)');


-- ============================================
-- AI Processing Queue (Optional - Phase 2)
-- ============================================
-- Queue for asynchronous AI processing jobs.
-- Not used in MVP but included for future expansion.

create table if not exists ai_processing_queue (
    id bigserial primary key,
    event_id bigint not null references all_events(id) on delete cascade,
    task_type varchar(50) not null,
    language varchar(10) not null default 'en',
    priority integer default 0,
    status varchar(20) not null default 'pending',
    retry_count integer default 0,
    max_retries integer default 3,
    error_message text,
    scheduled_at timestamptz not null default now(),
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    unique(event_id, task_type, language)
);

create index idx_ai_queue_status on ai_processing_queue(status, scheduled_at);
create index idx_ai_queue_task on ai_processing_queue(task_type, status);

comment on table ai_processing_queue is 
    'Queue for async AI processing jobs (Phase 2 feature)';
comment on column ai_processing_queue.task_type is 
    'Type of task: summary, quiz, chat_index';
comment on column ai_processing_queue.status is 
    'Status: pending, processing, completed, failed';