import React from "react";
import { useFragment, graphql } from "react-relay/hooks";
import { useTranslation } from "react-i18next";
import { LuSparkles } from "react-icons/lu";

import { AiSummary$key } from "./__generated__/AiSummary.graphql";
import { COLORS } from "../color";

const fragment = graphql`
  fragment AiSummary on AiSummary {
    summary
    model
    createdAt
    processingTimeMs
  }
`;

type Props = {
  fragmentRef: AiSummary$key;
};

export const AiSummary: React.FC<Props> = ({ fragmentRef }) => {
  const { t } = useTranslation();
  const data = useFragment(fragment, fragmentRef);

  if (!data) {
    return null;
  }

  return (
    <div css={{
      padding: "20px 22px",
      marginTop: "16px",
      backgroundColor: COLORS.neutral10,
      borderRadius: 8,
    }}>
      <div css={{
        display: "flex",
        alignItems: "center",
        marginBottom: "1rem",
        gap: "0.5rem",
      }}>
        <LuSparkles size={24} />
        <h3 css={{ margin: 0 }}>
          {t("video.ai-summary.title", "AI-Generated Summary")}
        </h3>
      </div>
      
      <div css={{
        lineHeight: 1.6,
        whiteSpace: "pre-wrap",
      }}>
        {data.summary}
      </div>
      
      <div css={{
        marginTop: "1rem",
        fontSize: "0.85rem",
        color: COLORS.neutral40,
        fontStyle: "italic",
      }}>
        {t("video.ai-summary.generated-by", "Generated by")} {data.model}
      </div>
    </div>
  );
};